supportLabel: question

supportComment: >
:wave: @{issue-author}, we use the issue tracker exclusively for bug reports
  and feature requests. However, this issue appears to be a support request.
  Please, use [Stackoverflow](https://www.stackoverflow.com) to get help.

close: true

lock: false

setLockReason: true